// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Animal
{
    public string AnimalId { get; set; }

    public string HabitatId { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string ScientificName { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Habitat Habitat { get; set; }
}