// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class EventStaff
{
    public string EventStaffId { get; set; }

    public string StaffId { get; set; }

    public string EventId { get; set; }

    public string RoleInEvent { get; set; }

    public virtual Event Event { get; set; }

    public virtual Staff Staff { get; set; }
}