// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Facility
{
    public string FacilityId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string LocationCoordinates { get; set; }

    public DateTime? OpeningHours { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}