// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClassLibrary.Models.Data;

public partial class Habitat
{
    public string HabitatId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    [JsonIgnore]
    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}