// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Image
{
    public string ImageId { get; set; }

    public string RefId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? UploadedDate { get; set; }
}