// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Location
{
    public string LocationId { get; set; }

    public string RefId { get; set; }

    public string Name { get; set; }

    public string X { get; set; }

    public string Y { get; set; }

    public string Description { get; set; }

    public string Activities { get; set; }
}