// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Order
{
    public string OrderId { get; set; }

    public string UserId { get; set; }

    public int? TotalAmount { get; set; }

    public decimal? TotalPrice { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? OrderDatetime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User User { get; set; }
}