// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class OrderItem
{
    public string OrderItemId { get; set; }

    public string OrderId { get; set; }

    public string ProductId { get; set; }

    public int? Quantity { get; set; }

    public decimal? PriceEach { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}