// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class Payment
{
    public string PaymentId { get; set; }

    public string OrderId { get; set; }

    public string Method { get; set; }

    public decimal? Amount { get; set; }

    public string Status { get; set; }

    public string ReferenceCode { get; set; }

    public DateTime? PaidAt { get; set; }
}