// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class QrScanLog
{
    public string ScanId { get; set; }

    public string ProductId { get; set; }

    public string QrCodeUrl { get; set; }

    public DateTime? ScannedAt { get; set; }

    public virtual Product Product { get; set; }
}