// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class RefreshToken
{
    public int RefreshTokenId { get; set; }

    public string UserId { get; set; }

    public string JwtTokenId { get; set; }

    public string Token { get; set; }

    public bool? IsValid { get; set; }

    public DateTime? ExpiresAt { get; set; }
}