// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary.Models.Data;

public partial class UserTicket
{
    public string UserTicketId { get; set; }

    public string UserId { get; set; }

    public string TicketId { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual User User { get; set; }
}